### ISSUE TITLE
Change LICENSE

### ISSUE THREAD

**Issue by augustresende** [bl4ckscor3/WoolPlates#1]
Please change the license from GPL to LGPL

GPL binaries cannot include any proprietary code, then this is very problematic to modders.

**Comment by bl4ckscor3** [comment]
Can you please elaborate? What do you want to do?

**Comment by augustresende** [comment]
https://fluendo.com/en/blog/post/gpl-vs-lgpl/

**Comment by augustresende** [comment]
GPL license does not allow the binary to be distributed along with proprietary codes, that is, it is legally forbidden to place this mod in a modpack that has proprietary mods, for example

**Comment by augustresende** [comment]
https://blog.jwf.io/2020/04/open-source-minecraft-bukkit-gpl/

**Comment by bl4ckscor3** [comment]
So? Using CurseForge's modpacks, I don't see an issue there as mod files are not distributed together, but are downloaded seperately. I also don't see how the whole Bukkit situation comes into play in this, as the license itself has very little to do with it. It's more about Mojang and the Bukkit Dev's relationship why this whole thing happened.

**Comment by bl4ckscor3** [comment]
Closing this. As I understand it, this is unnecessary, and judging by the fact that you have not replied to my latest comment, it seems you are no longer interested in this.
